language: ruby

cache:
  directories:
  - $HOME/protobuf

sudo: false

before_install:
  - ./install-protobuf.sh

# check what has been installed by listing contents of protobuf folder
script:
  - ls -R $HOME/protobuf
  - $HOME/protobuf/bin/protoc person.proto
