language: ruby

# cache:
#   directories:
#   - $HOME/protobuf

sudo: false

before_install:
  - bash install-protobuf2.sh

# check what has been installed by listing contents of protobuf folder
before_script:
  - ls -R $HOME/protobuf

# let's use protobuf
script:
  - $HOME/protobuf/bin/protoc --cpp_out=$PWD person.proto
  - ls -l
