language: ruby

# cache:
#   directories:
#   - $HOME/protobuf

sudo: false

before_install:
  - ./install-protobuf.sh

# to check what has been installed, list contents of protobuf folder
script:
  - ls -R $HOME/protobuf
